### PR TITLE
List structure

### PR DESCRIPTION
**Pull request by Obote**
### **What does this PR do**

- Set up a new project with webpack that is based on the Webpack exercise you have already completed
- Create an index.html file and write your HTML markup here
- Create an empty To Do List placeholder
- Create an index.js file and set an array of some simple to do tasks (array of objects
- Write a function to iterate over the tasks array and populate an HTML list item element for each task.

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Obote 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that has no linter check and node_module isn't' ignored.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi @Obote, 

descarga

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

# You have submitted a project, that doesn't have a professional README file.

image
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Obote** [comment]
Hello @franclobo & @brytebee  

Thank you for taking the time to review my project. However, I'm still unsure about what needs to be corrected. I have deleted and reconfigured linters, and they are running perfectly on my machine. I'm just not sure what exactly is causing the failure. Could you please provide more specific details or guidance on the issue? That would be greatly appreciated.

**Comment by franclobo** [comment]
Hello, @Obote 

I have edited the summary to be more descriptive about the reason why your PR was invalidated. I hope that it helps you. 😉

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES 🟡

Hi @Obote  👋🏽, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!



>  





## Required Changes ♻️
_Check the comments under the review._
- [ ] Good work adding the node_modules folder to your `.gitigonre`. ✔️ However, please kindly ensure to delete the node_modules folder from the respository too. 🤓 Currently, I can see you are including the node_modules folder inside the PR.
- [ ] Great work documenting your project using a professional README file. 💯 However, please kindly ensure to remove the Microverse Logo from the file.🤓 Also, please add instructions on how to run your application in the Usage section. 🔧
> Hint : `npm start`
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zainsadaqat — APPROVED** [review]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @Obote  👋 

### Things to appreciate
- [ ] Implemented the things requested by the previous code reviewers. 👍 

### Your project is complete!  There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 



Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
